# Generated by Django 2.2.1 on 2019-12-05 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0005_auto_20191205_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 5, 13, 17, 35, 444377)),
        ),
    ]
