# Generated by Django 2.2.1 on 2019-12-05 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0009_auto_20191205_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='complaint_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 5, 20, 12, 27, 247272)),
        ),
    ]
