# Generated by Django 2.2.1 on 2019-12-07 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0012_auto_20191207_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='action_taken',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='message',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 7, 10, 14, 1, 325187)),
        ),
    ]
