# Generated by Django 2.2.1 on 2019-12-07 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0014_auto_20191207_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 7, 12, 49, 15, 904693)),
        ),
    ]
