# Generated by Django 2.2.1 on 2019-12-07 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0017_auto_20191207_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 7, 12, 54, 56, 519268), null=True),
        ),
    ]
