# Generated by Django 2.2.1 on 2019-12-07 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0019_auto_20191207_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 7, 22, 22, 22, 533797), null=True),
        ),
    ]
