# Generated by Django 2.2.1 on 2019-12-10 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0020_auto_20191207_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='comments_aig',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 11, 39, 35, 215691), null=True),
        ),
    ]
