# Generated by Django 2.2.1 on 2019-12-10 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0021_auto_20191210_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_approved',
            new_name='is_approved_aig',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='is_reconsider',
            new_name='is_approved_dig',
        ),
        migrations.AddField(
            model_name='message',
            name='is_reconsider_aig',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_reconsider_dig',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 12, 3, 12, 345054), null=True),
        ),
    ]
