# Generated by Django 2.2.1 on 2019-12-10 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0022_auto_20191210_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_approved_dig',
            new_name='is_approved_dgp',
        ),
        migrations.AlterField(
            model_name='message',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 12, 22, 6, 534988), null=True),
        ),
    ]
