# Generated by Django 2.2.1 on 2019-12-10 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0023_auto_20191210_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 12, 42, 22, 120212), null=True),
        ),
    ]
