# Generated by Django 2.2.1 on 2019-12-10 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0024_auto_20191210_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_reconsider_dig',
            new_name='is_reconsider_dgp',
        ),
        migrations.AlterField(
            model_name='message',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 12, 43, 26, 978585), null=True),
        ),
    ]
