# Generated by Django 2.2.1 on 2019-12-25 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0026_auto_20191225_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 25, 13, 30, 30, 747964), null=True),
        ),
    ]
