# Generated by Django 2.2.1 on 2019-12-25 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0027_auto_20191225_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='logged_in',
            new_name='log_in',
        ),
        migrations.AlterField(
            model_name='message',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 25, 13, 31, 29, 938520), null=True),
        ),
    ]
