# Generated by Django 2.2.1 on 2019-12-25 08:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myportfolio', '0031_auto_20191225_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='logged_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loginuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 25, 13, 39, 20, 605859), null=True),
        ),
    ]
