# Generated by Django 2.2.1 on 2019-12-26 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0032_auto_20191225_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='logged_in',
        ),
        migrations.AlterField(
            model_name='message',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 26, 11, 5, 32, 211174), null=True),
        ),
    ]
